load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "RevenueCat",
    module_name = "RevenueCat",
    srcs = glob(["Sources/**/*.swift"]),
    # Include dependencies of RevenueCat here
    deps = [
        # Example: "@SomeDependency//:Target",
    ],
    visibility = ["//visibility:public"],
)